### ISSUE TITLE
cs-multi is missing CaptureStream.app file

### ISSUE THREAD

**Issue by DaddyJapan** [CSReviser/CS-Mult#1]
[cs-mult.docx](https://github.com/CSReviser/CS-Mult/files/8493358/cs-mult.docx)
**Describe the bug**
CS-Multi seems no files to run. Please see the attached file.

**To Reproduce**
just unzipped files.

**Expected behavior**
Under the install folder, there should be MacCaputureStream folder, and then under it, there should be License folder and CaptureStream.app just like 20220414 which works now as is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Monterey Version 12.3.1 MacBook Pro (14-inch, 2021)]

**Additional context**
New stylesheet and ffmpeg work with old CS-Multi. However, we need to put them to the right place.
[cs-mult.docx](https://github.com/CSReviser/CS-Mult/files/8493402/cs-mult.docx)

**Comment by CSReviser** [comment]
dmgファイル作成時にミスがありappが格納されていませんでした。修正して、差し替え済みです。
ご連絡ありがとうございました。
